base_url = "https://golmschenk.github.io/microlensing_ide_tutorial"

theme = "juice"

compile_sass = true
build_search_index = false

[markdown]
highlight_code = true

[extra]
juice_logo_name = "red_circle"
juice_logo_path = "red_circle.svg"